services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 10s
      timeout: 30s
      retries: 15

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # если используете HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # монтируем конфиг
      - ./ssl:/etc/letsencrypt  # если есть SSL
    depends_on:
      - backend